# Site settings
title: Constant Arguments
fullname: Arnon Zilca
# email:
description: "A programing blog"
baseurl: ""
url: "http://arnonzilca.github.io"
github_username: arnonzilca
stackoverflow_username: 3374591
linkedin_username: arnonzilca

# Build settings
markdown: kramdown
permalink: pretty

excerpt_separator: ''
